version: '3'

services:
  db:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'dw-db'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./app:/var/www
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: